#!/usr/bin/env bash

set -efu

function main {
  env PYTHON=python2.7 PIP=pip2.7 VENV="virtualenv -p python2.7" block compile virtualenv
  ln -nfs ../vendor/virtualenv/bin/letsencrypt bin/
  ln -nfs ../vendor/virtualenv/bin/letsencrypt-renewer bin/
}

main "$@"
