#!/usr/bin/env bash

set -efu

function main {
  block compile virtualenv27
  ln -nfs ../vendor/virtualenv/bin/letsencrypt bin/
  ln -nfs ../vendor/virtualenv/bin/letsencrypt-renewer bin/
}

main "$@"
